services:
  db:
    image: mysql
    container_name: picpay_project
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - picpay_data:/var/lib/mysql

volumes:
  picpay_data: